ReadExcelProcess/Controllers/ExcelController.cs
using Microsoft.AspNetCore.Mvc;
using ReadExcelProcess.DTO;
using ReadExcelProcess.Service;

namespace ReadExcelProcess.Controllers
{
    [Route("[controller]")]
    public class ExcelController : Controller
    {
        private readonly IExcelService _excelService;
        private readonly IDistanceMatrixService _distanceMatrixService;
        private readonly IDeviceImportService _deviceImportService;
        private readonly IProvinceService _provinceService;
        private readonly IOfficerImportService _officerImportService;
        private readonly IContractImportService _contractImportService;
        private readonly IDeviceMaintenanceService _deviceMaintenanceService;

        public ExcelController(IExcelService excelService, IDistanceMatrixService distanceMatrixService, IDeviceImportService deviceImportService,
            IProvinceService provinceService, IOfficerImportService officerImportService, IContractImportService contractImportService, IDeviceMaintenanceService deviceMaintenanceService)
        {
            _distanceMatrixService = distanceMatrixService;
            _excelService = excelService;
            _deviceImportService = deviceImportService;
            _provinceService = provinceService;
            _officerImportService = officerImportService;
            _contractImportService = contractImportService;
            _deviceMaintenanceService = deviceMaintenanceService;
        }

        [HttpPost("api/GetDistanceMatrix")]
        public async Task<IActionResult> GetDistanceMatrix([FromBody] List<string> addressList)
        {
            if (addressList == null || addressList.Count < 2)
                return BadRequest("Cần ít nhất 2 điểm để tính khoảng cách.");

            var matrix = await _distanceMatrixService.GetTravelTimeMatrix(addressList);

            // Chuyển mảng 2D sang danh sách List<List<double>>
            var result = ConvertMatrixToList(matrix);

            return Ok(result);
        }

        [HttpPost("api/import-devices")]
        public async Task<IActionResult> ImportDevicesFromExcel(IFormFile file)
        {
            try
            {
                var result = await _deviceImportService.ImportDevicesFromExcel(file);

                return Ok(new
                {
                    Status = "Success",
                    Total = result.Count,
                    Data = result
                });
            }
            catch (Exception ex)
            {
                return BadRequest(new
                {
                    Status = "Error",
                    Message = ex.Message
                });
            }
        }

        [HttpPost("api/import-travel-time")]
        public async Task<IActionResult> ImportCoordinateAndTravelTime(string supportCode)
        {
            try
            {
                var result = await _deviceImportService.ImportCoordinateAndTravelTime(supportCode);

                return Ok(new
                {
                    Status = "Success",
                    Total = result.Count,
                    Data = result
                });
            }
            catch (Exception ex)
            {
                return BadRequest(new
                {
                    Status = "Error",
                    Message = ex.Message
                });
            }
        }

        [HttpPost("api/import-officer")]
        public async Task<IActionResult> ImportOfficerFromExcel(IFormFile file)
        {
            try
            {
                var result = await _officerImportService.ImportOfficerFromExcel(file);

                return Ok(new
                {
                    Status = "Success",
                    Total = result.Count,
                    Data = result
                });
            }
            catch (Exception ex)
            {
                return BadRequest(new
                {
                    Status = "Error",
                    Message = ex.Message
                });
            }
        }

        [HttpPost("api/import-province-travel-time")]
        public async Task<IActionResult> ImportProvinceTravel([FromBody] ProvinceTravelDto model)
        {
            if (model == null || model.SupportCodes == null || model.SupportCodes.Count == 0)
            {
                return BadRequest("Danh sách SupportCode không hợp lệ");
            }

            var result = await _deviceImportService.ImportTravelTimeProvince(model.SupportCodes, model.ProvinceId);

            if (result.Count == 0)
            {
                return NotFound("Không tìm thấy thiết bị hoặc tỉnh thành phù hợp");
            }

            return Ok(new { Message = "Import thành công " + model.ProvinceId.ToString(), Total = result.Count(), Data = result });
        }


        [HttpPost("api/import-provinces")]
        public async Task<IActionResult> ImportProvinceFromExcel(IFormFile file)
        {
            try
            {
                var result = await _provinceService.ImportProvincesFromExcelAsync(file);

                return Ok(new
                {
                    Status = "Success",
                    Total = result.Count,
                    Data = result
                });
            }
            catch (Exception ex)
            {
                return BadRequest(new
                {
                    Status = "Error",
                    Message = ex.Message
                });
            }
        }

        [HttpPost("api/import-contracts")]
        public async Task<IActionResult> ImportContractFromExcel(IFormFile file)
        {
            try
            {
                var result = await _contractImportService.ImportContractsAsync(file);

                return Ok(new
                {
                    Status = "Success",
                    Total = result.Count,
                    Data = result
                });
            }
            catch (Exception ex)
            {
                return BadRequest(new
                {
                    Status = "Error",
                    Message = ex.Message
                });
            }
        }

        [HttpPost("generate-date")]
        public async Task<IActionResult> GenerateMaintenanceSchedules()
        {
            try
            {
                await _deviceMaintenanceService.GenerateMaintenanceSchedulesAsync();
                return Ok("Lịch bảo trì đã được tạo thành công.");
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Có lỗi xảy ra: {ex.Message}");
            }
        }

        [HttpPost("api/export-divisionDay")]
        public async Task<IActionResult> ExportExcel([FromBody] InputData inputData)
        {
            var fileContent = await _excelService.ExportDivisionDay(inputData);

            string fileName = $"DivisionDay_{DateTime.Now:yyyyMMdd_HHmmss}.xlsx";

            return File(fileContent, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
        }

        private List<List<double>> ConvertMatrixToList(double[,] matrix)
        {
            int rows = matrix.GetLength(0);
            int cols = matrix.GetLength(1);
            var list = new List<List<double>>(rows);

            for (int i = 0; i < rows; i++)
            {
                var row = new List<double>(cols);
                for (int j = 0; j < cols; j++)
                {
                    row.Add(matrix[i, j]);
                }
                list.Add(row);
            }

            return list;
        }
    }
}

ReadExcelProcess/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReadExcelProcess</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ReadExcelProcess.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ReadExcelProcess</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Excel" asp-action="Index">Tính thời gian di chuyển</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Excel" asp-action="TimeWork">Phân công làm việc</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ReadExcelProcess - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>